// <auto-generated />
namespace CodeFirst.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Install : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Install));
        
        string IMigrationMetadata.Id
        {
            get { return "201508090813577_Install"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
